### ISSUE TITLE
Matlab Code Location

### ISSUE THREAD

**Issue by tcpekin** [ercius/openNCEM#8]
I forget during the discussion we had in person when creating this repo, but are we going to split the top level folder structure into Python and Matlab folders such that there are only two top level folders and the few necessary text files (.gitignore, README, LICENSE)? This would require moving docs, tools, and ncempy into a python folder and updating any necessary cross-references. On the other hand, we could leave things the way they are and only add a specific Matlab folder. 

Tom

**Comment by fniekiel** [comment]
Sorry for the late response.

In the initial discussion we decided to have matlab and python things in different folders, but have the tools (or projects) in a shared folder. This is more like the second option you mention.

I still think this is the best way, because it allows the tools/projects to use whatever is necessary from the libraries. Having a subfolder for each language would mean separate tools and also separate documentation.
